# Generated by Django 4.1.2 on 2023-05-31 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('Id_juego', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=20)),
                ('plataforma', models.CharField(max_length=20)),
                ('nombre_juego', models.CharField(max_length=30)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stock', models.IntegerField(default=100)),
                ('disponible', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellidos', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('contrasenna', models.CharField(max_length=20)),
                ('activo', models.IntegerField()),
            ],
        ),
    ]
