# Generated by Django 4.1.2 on 2023-05-31 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0002_inventario_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='id_genero',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.AlterField(
            model_name='inventario',
            name='disponible',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('no_disponible', 'No disponible')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Alumno',
        ),
        migrations.DeleteModel(
            name='Genero',
        ),
    ]
