# Generated by Django 4.1.2 on 2023-05-31 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0003_remove_alumno_id_genero_delete_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='Id_juego',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
