# Generated by Django 4.1.2 on 2023-06-14 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0006_categoria_plataforma_remove_inventario_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='Id_categoria',
            field=models.AutoField(db_column='idCategoria', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='Id_categoria',
            field=models.ForeignKey(db_column='idCategoria', on_delete=django.db.models.deletion.CASCADE, to='venta.categoria'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='Id_plataforma',
            field=models.ForeignKey(db_column='idPlataforma', on_delete=django.db.models.deletion.CASCADE, to='venta.plataforma'),
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='Id_plataforma',
            field=models.AutoField(db_column='idPlataforma', primary_key=True, serialize=False),
        ),
    ]
