# Generated by Django 4.1.2 on 2023-05-31 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellidos', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=100, unique=True)),
                ('contrasenna', models.CharField(max_length=20)),
                ('activo', models.IntegerField()),
            ],
        ),
    ]
