# Generated by Django 4.1.2 on 2023-05-31 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuarios_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='id_usuario',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
