# Generated by Django 4.1.2 on 2023-06-14 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0005_alter_inventario_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('Id_categoria', models.AutoField(db_column='idCategoria', default='', primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('Id_plataforma', models.AutoField(db_column='idPlataforma', default='', primary_key=True, serialize=False)),
                ('plataforma', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='plataforma',
        ),
        migrations.AlterField(
            model_name='inventario',
            name='Id_juego',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='inventario',
            name='Id_categoria',
            field=models.ForeignKey(db_column='idCategoria', default='', on_delete=django.db.models.deletion.CASCADE, to='venta.categoria'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='Id_plataforma',
            field=models.ForeignKey(db_column='idPlataforma', default='', on_delete=django.db.models.deletion.CASCADE, to='venta.plataforma'),
        ),
    ]
