# Generated by Django 4.1.2 on 2023-06-30 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0010_inventario_id_coleccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='Id_coleccion',
            field=models.ForeignKey(db_column='idColeccion', on_delete=django.db.models.deletion.CASCADE, to='venta.coleccion'),
        ),
    ]
